// Curated emoji dataset for the in-chat picker.
// Format: [char, keywords]
export interface EmojiEntry { char: string; keywords: string; category: string; }

export const EMOJI_DATA: EmojiEntry[] = [
  // Smileys
  { char: '😀', keywords: 'grinning happy smile face', category: 'Smileys' },
  { char: '😃', keywords: 'smiley happy face', category: 'Smileys' },
  { char: '😄', keywords: 'smile happy laugh', category: 'Smileys' },
  { char: '😁', keywords: 'beaming grin happy', category: 'Smileys' },
  { char: '😆', keywords: 'laugh squint happy', category: 'Smileys' },
  { char: '😅', keywords: 'sweat laugh nervous', category: 'Smileys' },
  { char: '🤣', keywords: 'rofl laughing rolling', category: 'Smileys' },
  { char: '😂', keywords: 'joy tears laugh lol', category: 'Smileys' },
  { char: '🙂', keywords: 'slight smile', category: 'Smileys' },
  { char: '🙃', keywords: 'upside down silly', category: 'Smileys' },
  { char: '😉', keywords: 'wink flirt', category: 'Smileys' },
  { char: '😊', keywords: 'blush smile happy', category: 'Smileys' },
  { char: '😇', keywords: 'innocent halo angel', category: 'Smileys' },
  { char: '🥰', keywords: 'love hearts adore', category: 'Smileys' },
  { char: '😍', keywords: 'heart eyes love', category: 'Smileys' },
  { char: '🤩', keywords: 'star struck wow', category: 'Smileys' },
  { char: '😘', keywords: 'kiss blow', category: 'Smileys' },
  { char: '😗', keywords: 'kiss', category: 'Smileys' },
  { char: '😚', keywords: 'kiss closed eyes', category: 'Smileys' },
  { char: '😙', keywords: 'kiss smiling', category: 'Smileys' },
  { char: '🥲', keywords: 'smile tear happy sad', category: 'Smileys' },
  { char: '😋', keywords: 'yum tongue tasty', category: 'Smileys' },
  { char: '😛', keywords: 'tongue out', category: 'Smileys' },
  { char: '😜', keywords: 'wink tongue silly', category: 'Smileys' },
  { char: '🤪', keywords: 'zany crazy goofy', category: 'Smileys' },
  { char: '😝', keywords: 'squint tongue', category: 'Smileys' },
  { char: '🤑', keywords: 'money mouth rich', category: 'Smileys' },
  { char: '🤗', keywords: 'hug hugging', category: 'Smileys' },
  { char: '🤭', keywords: 'oops giggle hand mouth', category: 'Smileys' },
  { char: '🤫', keywords: 'shush quiet shh', category: 'Smileys' },
  { char: '🤔', keywords: 'thinking hmm', category: 'Smileys' },
  { char: '🤐', keywords: 'zipper lips quiet', category: 'Smileys' },
  { char: '🤨', keywords: 'raised eyebrow skeptical', category: 'Smileys' },
  { char: '😐', keywords: 'neutral meh', category: 'Smileys' },
  { char: '😑', keywords: 'expressionless blank', category: 'Smileys' },
  { char: '😶', keywords: 'no mouth speechless', category: 'Smileys' },
  { char: '😏', keywords: 'smirk smug', category: 'Smileys' },
  { char: '😒', keywords: 'unamused meh', category: 'Smileys' },
  { char: '🙄', keywords: 'eye roll', category: 'Smileys' },
  { char: '😬', keywords: 'grimace awkward', category: 'Smileys' },
  { char: '🤥', keywords: 'lying liar pinocchio', category: 'Smileys' },
  { char: '😌', keywords: 'relieved calm', category: 'Smileys' },
  { char: '😔', keywords: 'pensive sad', category: 'Smileys' },
  { char: '😪', keywords: 'sleepy tired', category: 'Smileys' },
  { char: '🤤', keywords: 'drool', category: 'Smileys' },
  { char: '😴', keywords: 'sleeping zzz', category: 'Smileys' },
  { char: '😷', keywords: 'mask sick', category: 'Smileys' },
  { char: '🤒', keywords: 'sick thermometer', category: 'Smileys' },
  { char: '🤕', keywords: 'hurt bandage', category: 'Smileys' },
  { char: '🤢', keywords: 'nauseated sick green', category: 'Smileys' },
  { char: '🤮', keywords: 'vomit puke', category: 'Smileys' },
  { char: '🤧', keywords: 'sneeze sick', category: 'Smileys' },
  { char: '🥵', keywords: 'hot heat sweat', category: 'Smileys' },
  { char: '🥶', keywords: 'cold freezing', category: 'Smileys' },
  { char: '🥴', keywords: 'woozy dizzy drunk', category: 'Smileys' },
  { char: '😵', keywords: 'dizzy ko', category: 'Smileys' },
  { char: '🤯', keywords: 'mind blown exploding', category: 'Smileys' },
  { char: '🤠', keywords: 'cowboy hat', category: 'Smileys' },
  { char: '🥳', keywords: 'party celebrate', category: 'Smileys' },
  { char: '😎', keywords: 'cool sunglasses', category: 'Smileys' },
  { char: '🤓', keywords: 'nerd glasses', category: 'Smileys' },
  { char: '🧐', keywords: 'monocle inspect', category: 'Smileys' },
  { char: '😕', keywords: 'confused', category: 'Smileys' },
  { char: '😟', keywords: 'worried', category: 'Smileys' },
  { char: '🙁', keywords: 'slight frown sad', category: 'Smileys' },
  { char: '☹️', keywords: 'frown sad', category: 'Smileys' },
  { char: '😮', keywords: 'open mouth wow surprise', category: 'Smileys' },
  { char: '😯', keywords: 'hushed surprise', category: 'Smileys' },
  { char: '😲', keywords: 'astonished shocked', category: 'Smileys' },
  { char: '😳', keywords: 'flushed blush embarrassed', category: 'Smileys' },
  { char: '🥺', keywords: 'pleading begging puppy', category: 'Smileys' },
  { char: '😦', keywords: 'frown open mouth', category: 'Smileys' },
  { char: '😧', keywords: 'anguished', category: 'Smileys' },
  { char: '😨', keywords: 'fearful scared', category: 'Smileys' },
  { char: '😰', keywords: 'anxious sweat', category: 'Smileys' },
  { char: '😥', keywords: 'sad relieved', category: 'Smileys' },
  { char: '😢', keywords: 'cry tear sad', category: 'Smileys' },
  { char: '😭', keywords: 'loud cry sob', category: 'Smileys' },
  { char: '😱', keywords: 'scream fear shocked', category: 'Smileys' },
  { char: '😖', keywords: 'confounded frustrated', category: 'Smileys' },
  { char: '😣', keywords: 'persevere struggle', category: 'Smileys' },
  { char: '😞', keywords: 'disappointed sad', category: 'Smileys' },
  { char: '😓', keywords: 'sweat downcast', category: 'Smileys' },
  { char: '😩', keywords: 'weary tired', category: 'Smileys' },
  { char: '😫', keywords: 'tired exhausted', category: 'Smileys' },
  { char: '🥱', keywords: 'yawn bored', category: 'Smileys' },
  { char: '😤', keywords: 'huff steam angry', category: 'Smileys' },
  { char: '😡', keywords: 'pouting angry rage', category: 'Smileys' },
  { char: '😠', keywords: 'angry mad', category: 'Smileys' },
  { char: '🤬', keywords: 'swearing cursing', category: 'Smileys' },
  { char: '😈', keywords: 'devil imp smiling', category: 'Smileys' },
  { char: '👿', keywords: 'angry devil imp', category: 'Smileys' },
  { char: '💀', keywords: 'skull dead', category: 'Smileys' },
  { char: '☠️', keywords: 'skull crossbones', category: 'Smileys' },
  { char: '💩', keywords: 'poop pile', category: 'Smileys' },
  { char: '🤡', keywords: 'clown', category: 'Smileys' },
  { char: '👹', keywords: 'ogre monster', category: 'Smileys' },
  { char: '👺', keywords: 'goblin', category: 'Smileys' },
  { char: '👻', keywords: 'ghost spooky', category: 'Smileys' },
  { char: '👽', keywords: 'alien ufo', category: 'Smileys' },
  { char: '🤖', keywords: 'robot bot', category: 'Smileys' },
  // Gestures
  { char: '👍', keywords: 'thumbs up like yes ok', category: 'Gestures' },
  { char: '👎', keywords: 'thumbs down dislike no', category: 'Gestures' },
  { char: '👌', keywords: 'ok perfect', category: 'Gestures' },
  { char: '🤌', keywords: 'pinched fingers italian', category: 'Gestures' },
  { char: '🤏', keywords: 'pinching small', category: 'Gestures' },
  { char: '✌️', keywords: 'peace victory', category: 'Gestures' },
  { char: '🤞', keywords: 'fingers crossed luck hope', category: 'Gestures' },
  { char: '🤟', keywords: 'love you rock', category: 'Gestures' },
  { char: '🤘', keywords: 'rock metal horns', category: 'Gestures' },
  { char: '🤙', keywords: 'call shaka', category: 'Gestures' },
  { char: '👈', keywords: 'point left', category: 'Gestures' },
  { char: '👉', keywords: 'point right', category: 'Gestures' },
  { char: '👆', keywords: 'point up', category: 'Gestures' },
  { char: '👇', keywords: 'point down', category: 'Gestures' },
  { char: '☝️', keywords: 'index up one', category: 'Gestures' },
  { char: '✋', keywords: 'hand stop high five', category: 'Gestures' },
  { char: '🤚', keywords: 'raised back hand', category: 'Gestures' },
  { char: '🖐️', keywords: 'hand fingers splayed', category: 'Gestures' },
  { char: '🖖', keywords: 'spock vulcan', category: 'Gestures' },
  { char: '👋', keywords: 'wave hello hi bye', category: 'Gestures' },
  { char: '🤝', keywords: 'handshake deal', category: 'Gestures' },
  { char: '👏', keywords: 'clap applause bravo', category: 'Gestures' },
  { char: '🙌', keywords: 'praise hands raised', category: 'Gestures' },
  { char: '👐', keywords: 'open hands', category: 'Gestures' },
  { char: '🤲', keywords: 'palms up offer', category: 'Gestures' },
  { char: '🙏', keywords: 'pray thanks please', category: 'Gestures' },
  { char: '✊', keywords: 'fist solidarity', category: 'Gestures' },
  { char: '👊', keywords: 'fist bump punch', category: 'Gestures' },
  { char: '🤛', keywords: 'left fist bump', category: 'Gestures' },
  { char: '🤜', keywords: 'right fist bump', category: 'Gestures' },
  { char: '💪', keywords: 'muscle strong flex', category: 'Gestures' },
  { char: '🦾', keywords: 'mechanical arm', category: 'Gestures' },
  { char: '🦿', keywords: 'mechanical leg', category: 'Gestures' },
  // Hearts/Symbols
  { char: '❤️', keywords: 'red heart love', category: 'Symbols' },
  { char: '🧡', keywords: 'orange heart', category: 'Symbols' },
  { char: '💛', keywords: 'yellow heart', category: 'Symbols' },
  { char: '💚', keywords: 'green heart', category: 'Symbols' },
  { char: '💙', keywords: 'blue heart', category: 'Symbols' },
  { char: '💜', keywords: 'purple heart', category: 'Symbols' },
  { char: '🖤', keywords: 'black heart', category: 'Symbols' },
  { char: '🤍', keywords: 'white heart', category: 'Symbols' },
  { char: '🤎', keywords: 'brown heart', category: 'Symbols' },
  { char: '💔', keywords: 'broken heart', category: 'Symbols' },
  { char: '❣️', keywords: 'heart exclamation', category: 'Symbols' },
  { char: '💕', keywords: 'two hearts love', category: 'Symbols' },
  { char: '💞', keywords: 'revolving hearts', category: 'Symbols' },
  { char: '💓', keywords: 'beating heart', category: 'Symbols' },
  { char: '💗', keywords: 'growing heart', category: 'Symbols' },
  { char: '💖', keywords: 'sparkling heart', category: 'Symbols' },
  { char: '💘', keywords: 'heart arrow cupid', category: 'Symbols' },
  { char: '💝', keywords: 'heart ribbon gift', category: 'Symbols' },
  { char: '💟', keywords: 'heart decoration', category: 'Symbols' },
  { char: '☮️', keywords: 'peace', category: 'Symbols' },
  { char: '✝️', keywords: 'cross christian', category: 'Symbols' },
  { char: '☪️', keywords: 'star crescent islam', category: 'Symbols' },
  { char: '🕉️', keywords: 'om hindu', category: 'Symbols' },
  { char: '☸️', keywords: 'dharma buddhist', category: 'Symbols' },
  { char: '✡️', keywords: 'star david judaism', category: 'Symbols' },
  { char: '⚛️', keywords: 'atom science', category: 'Symbols' },
  { char: '♻️', keywords: 'recycle', category: 'Symbols' },
  { char: '✅', keywords: 'check mark yes done', category: 'Symbols' },
  { char: '❌', keywords: 'cross x no wrong', category: 'Symbols' },
  { char: '❎', keywords: 'negative cross', category: 'Symbols' },
  { char: '✔️', keywords: 'check tick yes', category: 'Symbols' },
  { char: '❓', keywords: 'question', category: 'Symbols' },
  { char: '❗', keywords: 'exclamation', category: 'Symbols' },
  { char: '⁉️', keywords: 'interrobang', category: 'Symbols' },
  { char: '‼️', keywords: 'double exclamation', category: 'Symbols' },
  { char: '⭐', keywords: 'star', category: 'Symbols' },
  { char: '🌟', keywords: 'glowing star', category: 'Symbols' },
  { char: '✨', keywords: 'sparkles', category: 'Symbols' },
  { char: '⚡', keywords: 'lightning bolt zap', category: 'Symbols' },
  { char: '🔥', keywords: 'fire lit hot flame', category: 'Symbols' },
  { char: '💥', keywords: 'boom explosion', category: 'Symbols' },
  { char: '💯', keywords: '100 hundred perfect', category: 'Symbols' },
  { char: '💢', keywords: 'anger symbol', category: 'Symbols' },
  { char: '💫', keywords: 'dizzy stars', category: 'Symbols' },
  { char: '💨', keywords: 'dash wind', category: 'Symbols' },
  { char: '💦', keywords: 'sweat drops water', category: 'Symbols' },
  { char: '🎉', keywords: 'party popper celebrate', category: 'Symbols' },
  { char: '🎊', keywords: 'confetti ball party', category: 'Symbols' },
  { char: '🎈', keywords: 'balloon party', category: 'Symbols' },
  { char: '🎁', keywords: 'gift present', category: 'Symbols' },
  { char: '🏆', keywords: 'trophy winner gg', category: 'Symbols' },
  { char: '🥇', keywords: 'gold medal first', category: 'Symbols' },
  { char: '🥈', keywords: 'silver medal second', category: 'Symbols' },
  { char: '🥉', keywords: 'bronze medal third', category: 'Symbols' },
  { char: '🎖️', keywords: 'military medal', category: 'Symbols' },
  { char: '🏅', keywords: 'sports medal', category: 'Symbols' },
  // Game / Objects
  { char: '🎲', keywords: 'dice game roll', category: 'Game' },
  { char: '🎯', keywords: 'target bullseye', category: 'Game' },
  { char: '🎮', keywords: 'controller gamepad', category: 'Game' },
  { char: '🕹️', keywords: 'joystick arcade', category: 'Game' },
  { char: '🎰', keywords: 'slot machine', category: 'Game' },
  { char: '🃏', keywords: 'joker card', category: 'Game' },
  { char: '🀄', keywords: 'mahjong', category: 'Game' },
  { char: '🎴', keywords: 'flower cards', category: 'Game' },
  { char: '♟️', keywords: 'chess pawn', category: 'Game' },
  { char: '♠️', keywords: 'spade card', category: 'Game' },
  { char: '♥️', keywords: 'heart card', category: 'Game' },
  { char: '♦️', keywords: 'diamond card', category: 'Game' },
  { char: '♣️', keywords: 'club card', category: 'Game' },
  { char: '🧩', keywords: 'puzzle piece', category: 'Game' },
  { char: '🎨', keywords: 'art palette', category: 'Game' },
  { char: '🎭', keywords: 'theater masks', category: 'Game' },
  { char: '⚽', keywords: 'soccer football', category: 'Game' },
  { char: '🏀', keywords: 'basketball', category: 'Game' },
  { char: '🏈', keywords: 'football american', category: 'Game' },
  { char: '⚾', keywords: 'baseball', category: 'Game' },
  { char: '🎾', keywords: 'tennis', category: 'Game' },
  { char: '🥊', keywords: 'boxing glove fight', category: 'Game' },
  { char: '🔪', keywords: 'knife kill', category: 'Game' },
  { char: '🗡️', keywords: 'dagger sword', category: 'Game' },
  { char: '⚔️', keywords: 'crossed swords battle', category: 'Game' },
  { char: '🛡️', keywords: 'shield defense', category: 'Game' },
  { char: '💣', keywords: 'bomb', category: 'Game' },
  // Food
  { char: '🍕', keywords: 'pizza food', category: 'Food' },
  { char: '🍔', keywords: 'burger food', category: 'Food' },
  { char: '🍟', keywords: 'fries chips', category: 'Food' },
  { char: '🌭', keywords: 'hot dog', category: 'Food' },
  { char: '🌮', keywords: 'taco', category: 'Food' },
  { char: '🌯', keywords: 'burrito', category: 'Food' },
  { char: '🥪', keywords: 'sandwich', category: 'Food' },
  { char: '🍰', keywords: 'cake slice', category: 'Food' },
  { char: '🎂', keywords: 'birthday cake', category: 'Food' },
  { char: '🍩', keywords: 'donut', category: 'Food' },
  { char: '🍪', keywords: 'cookie', category: 'Food' },
  { char: '🍫', keywords: 'chocolate bar', category: 'Food' },
  { char: '🍿', keywords: 'popcorn', category: 'Food' },
  { char: '🍺', keywords: 'beer mug', category: 'Food' },
  { char: '🍻', keywords: 'cheers beers', category: 'Food' },
  { char: '🥂', keywords: 'champagne cheers toast', category: 'Food' },
  { char: '🍷', keywords: 'wine glass', category: 'Food' },
  { char: '☕', keywords: 'coffee tea hot', category: 'Food' },
  // Nature
  { char: '🌈', keywords: 'rainbow', category: 'Nature' },
  { char: '☀️', keywords: 'sun sunny', category: 'Nature' },
  { char: '🌙', keywords: 'moon night', category: 'Nature' },
  { char: '⭐', keywords: 'star night', category: 'Nature' },
  { char: '☁️', keywords: 'cloud', category: 'Nature' },
  { char: '⛈️', keywords: 'thunderstorm', category: 'Nature' },
  { char: '🌊', keywords: 'wave ocean water', category: 'Nature' },
  { char: '🌸', keywords: 'cherry blossom flower', category: 'Nature' },
  { char: '🌺', keywords: 'hibiscus flower', category: 'Nature' },
  { char: '🌻', keywords: 'sunflower', category: 'Nature' },
  { char: '🌷', keywords: 'tulip flower', category: 'Nature' },
  { char: '🌹', keywords: 'rose flower', category: 'Nature' },
  { char: '🌴', keywords: 'palm tree', category: 'Nature' },
  { char: '🌵', keywords: 'cactus', category: 'Nature' },
  { char: '🐶', keywords: 'dog puppy', category: 'Nature' },
  { char: '🐱', keywords: 'cat kitten', category: 'Nature' },
  { char: '🐭', keywords: 'mouse', category: 'Nature' },
  { char: '🐹', keywords: 'hamster', category: 'Nature' },
  { char: '🐰', keywords: 'rabbit bunny', category: 'Nature' },
  { char: '🦊', keywords: 'fox', category: 'Nature' },
  { char: '🐻', keywords: 'bear', category: 'Nature' },
  { char: '🐼', keywords: 'panda', category: 'Nature' },
  { char: '🐨', keywords: 'koala', category: 'Nature' },
  { char: '🐯', keywords: 'tiger', category: 'Nature' },
  { char: '🦁', keywords: 'lion', category: 'Nature' },
  { char: '🐮', keywords: 'cow', category: 'Nature' },
  { char: '🐷', keywords: 'pig', category: 'Nature' },
  { char: '🐸', keywords: 'frog', category: 'Nature' },
  { char: '🐵', keywords: 'monkey', category: 'Nature' },
  { char: '🙈', keywords: 'see no evil monkey', category: 'Nature' },
  { char: '🙉', keywords: 'hear no evil monkey', category: 'Nature' },
  { char: '🙊', keywords: 'speak no evil monkey', category: 'Nature' },
  { char: '🐔', keywords: 'chicken', category: 'Nature' },
  { char: '🐧', keywords: 'penguin', category: 'Nature' },
  { char: '🦄', keywords: 'unicorn', category: 'Nature' },
  { char: '🐝', keywords: 'bee', category: 'Nature' },
  { char: '🐞', keywords: 'ladybug', category: 'Nature' },
];

export const EMOJI_CATEGORIES = ['Smileys', 'Gestures', 'Symbols', 'Game', 'Food', 'Nature'] as const;